version: '3'
services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env
    volumes:
      - db:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - ./back-end/.env

  react_app:
    build: ./front-end
    container_name: react_app
    volumes:
      - build_react:/var/www/html
    depends_on:
      - node_app

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - react_app

volumes:
  db:
  build_react:
